### ISSUE TITLE
tried to do a git clone recursive on a windows 10 machine

### ISSUE THREAD

**Issue by ZanzyTHEbar** [CamelCaseCam/CadBerry#5]
Main branch

This is the error

```bash
Submodule path 'CadBerry/CadBerry/vendor/GLFW': checked out '8bbfbe7a87977f9c18d1b9280848d72bd5dff655' fatal: remote error: upload-pack: not our ref 3819090d2cdcb2928e89942643cb6873d5c75f94e-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed allow-tip-sha1-in-want allow-reachable-sha1-in-want no-done symref=HEAD:refs/heads/docking filter object-format=sha1 agent=git/github-g169cc06abf93 fatal: the remote end hung up unexpectedly Fetched in submodule path 'CadBerry/CadBerry/vendor/IMGUI', but it did not contain 3819090d2cdcb2928e89942643cb6873d5c75f94. Direct fetching of that commit failed.
```

P.S The installer did not work either - said that the exe could not run on my machine.

**Comment by CamelCaseCam** [comment]
I'm away for the next week, so I won't be able to fix any of this until I get back. 

The submodule thing is a known bug that I've been having problems with for a while. I probably just have local changes I forgot to push. 

The installer is a more serious problem. Do you have visual studio (with C++ components)? I may have forgotten to include the MSVC runtime dll (CadBerry uses dynamic linking to the runtime library)

Regardless, the parser is so completely broken right now that it's going to take a week or two until everything's back in working order.

**Comment by ZanzyTHEbar** [comment]
Understood, thank you. I will try again with my other machine (has VS 2022 with C++ components) and get back to you.

**Comment by CamelCaseCam** [comment]
The missing libraries is fixed now, and the submodule error should be fixed too.
